### ISSUE TITLE
Using NetlinkCtDestroy do not work

### ISSUE THREAD

**Issue by daddylhz** [florianl/go-conntrack#4] opened 2019-04-15 06:16 UTC
use RegisterFiltered with NetlinkCtDestroy, no message will receive.

**Comment by florianl** [comment] 2019-04-15 08:23
Hi!
Thanks for your feedback! Can you please a little more input?

### What did you do?





### What did you expect to see?

### What did you see instead?

**Comment by florianl** [comment] 2019-04-17 09:33
Please see `TestLinuxConntrackDeleteEntry()` for an example how `Delete()` can be used.

**Comment by eay** [comment] 2019-07-09 08:28
I think this relates to this issue:
I'm playing with implementing a conntrack(1) clone on top of your package, and using Register(), I'm not seeing ct.NetlinkCtDestroy NetlinkGroup events.
New and Update, yes, Destroy no.

Digger further, I belive it is an issue in the use of
return os.NewSyscallError("setsockopt", c.s.SetSockoptInt(
unix.SOL_NETLINK,
unix.NETLINK_ADD_MEMBERSHIP,
int(group),
))
in conn_linux.go function JoinGroup.
I belivethe problem is that the setsockoptInt() version of group is not a bitmask value, as defined in
linux/netfilter/nfnetlink_compat.h, but rather the values defined in
enum nfnetlink_groups in linux/netfilter/nfnetlink.h.
You are calling setsockopt once for each group, but the bitmask values of
1, 2, 4, 8, 16, 32 are not registering 3, which is the enum for NFNLGRP_CONNTRACK_DESTROY.

I've done an evil hack of
group = uint32(bits.TrailingZeros8(uint8(group)) + 1)
around JoinGroup/LeaveGroup
seems to let me get events but no data. len(Conn) == 0

**Comment by florianl** [comment] 2019-07-10 15:39
With https://github.com/florianl/go-conntrack/pull/7 being merged, this issue can be closed. Am I right?

**Comment by eay** [comment] 2019-07-17 02:57
Yes, all looks good now. The only outstanding issues is #8 
thanks

**Comment by florianl** [comment] 2019-07-17 18:46
Thanks for the feedback. Then I will close this issue. Please feel free to reopen it, if needed or create a new one.

**Closed by florianl** 2019-07-17 18:46 UTC
